[package]
name = "cogbuilder"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.64"
bytemuck = "1.11.0"
thread_local = "1.1.4"
zstd = "0.12.1"
